import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

const sourceRevision = '525f9b560de45753a5ea01069454e72e9aa541c6'
const sourceUrl = `https://raw.githubusercontent.com/hermitdave/FrequencyWords/${sourceRevision}/content/2018/en/en_full.txt`
const outputPath = fileURLToPath(new URL('../src/utils/freq50k.ts', import.meta.url))

const response = await fetch(sourceUrl)
if (!response.ok) throw new Error(`FrequencyWords download failed: ${response.status}`)

const lines = (await response.text()).trimEnd().split(/\r?\n/).slice(0, 50_000)
if (lines.length !== 50_000 || lines.some((line) => !/^[^\s]+\s+\d+$/.test(line))) {
  throw new Error('FrequencyWords source did not contain the expected 50,000 word/count rows')
}

const escaped = lines.join('\n')
  .replaceAll('\\', '\\\\')
  .replaceAll('`', '\\`')
  .replaceAll('${', '\\${')
const output = `// Generated by scripts/generate-freq50k.mjs; do not edit by hand.
// Source: ${sourceUrl}
// FrequencyWords content is licensed CC BY-SA 4.0; see docs/frequency-list.md.
export const FREQ50K = \`
${escaped}
\`
`

if (process.argv.includes('--check')) {
  const current = await readFile(outputPath, 'utf8')
  if (current !== output) {
    console.error('src/utils/freq50k.ts is stale; run npm run generate:freq50k')
    process.exitCode = 1
  }
} else {
  await writeFile(outputPath, output)
  console.log(`Wrote ${lines.length} rows to src/utils/freq50k.ts`)
}
